version = 1

[[analyzers]]
name = "secrets"
enabled = true

[[analyzers]]
name = "github.com/sourya-deepsource/django-antipatterns"
enabled = true

#[[analyzers]]
# name = "github.com/sourya/django-antipatterns"
# enabled = true

# [[analyzers]]
# name = "gitlab.com/sourya/django-antipatterns"
# enabled = true

# [[analyzers]]
# name = "gitlab.com/sourya-deepsource/django-antipatterns"
# enabled = true

# [[analyzers]]
# name = "bitbucket.org/wahi/django-antipatterns"
# enabled = true
